wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1687428705.871077
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.6.9
      5: 0.13.5
      6: 4.18.0
      8:
      - 1
      - 5
